import java.io.*;
import java.util.*;
class cricket_game
{
	public static void main(String args[])
	{
		Scanner sc=new Scanner(System.in);
		Random rand = new Random();
		int runs=0;
		int computer=0;
     	int score=0;
		System.out.print("\n\n\t\t\t\t\t\t\t\t\t\t\t      *WELCOME TO THE CRICKET GAME*");
		System.out.print("\n\n\t\t\t\t\t\t\t\t\t\t$ ENTER ANY NUMBER BETWEEN 1 TO 6 AS THEY WILL BE YOUR RUNS");
		System.out.print("\n\n\t\t\t\t\t\t\t\t\t\t$ IF NUMBER ENTERED BY YOU AND NUMBER GENERATED BY COMPUTER IS SAME THEN\n\t\t\t\t\t\t\t\t\t\t  YOU WILL BE DECLARED AS OUT");
		System.out.print("\n\n\t\t\t\t\t\t\t\t\t\t$ IF COMPUTER GENERATE NUMBER 0 THEN IT WILL BE WIDE BALL");
		System.out.print("\n\n\t\t\t\t\t\t\t\t\t\t$ THE NUMBER ON WHICH YOU WILL DECLARED OUT WILL NOT BE CONSIDERED");
		System.out.print("\n\n\t\t\t\t\t\t\t\t\t\t$ HAVE FUN!!!!!!");
		System.out.print("\n\n\t\t\t\t\t\t\t\t---------------------------------------------------------------------------");
		while(true)
	  {
		computer =rand.nextInt(7);
		
       //wide ball
	   if(computer==0)
		 {
			 System.out.println("\n\t\t\t\t\t\t\t\t          => Heres a wide ball from computer !! One run Bonus ");
			 runs++;
			 continue;
		 }
		 //Runs entry
		 
		 System.out.print("\n\t\t\t\t\t\t\t\t          => How many run you want to cover in this ball-:");
		 score=sc.nextInt();
	 
	 //invalid runs entry  
	   if(score>=7)
	      {
		   System.out.println("\n\t\t\t\t\t\t\t\t          --> Maximum amount of run You will get in a ball is 6 runs not "+score+" runs");
		   continue;
	     }		   
	//out check
		 if(score==computer)
		{
			
			System.out.println("\n\t\t\t\t\t\t\t\t          >> OOPSS!!! You are out!!");
			System.out.println("\n\t\t\t\t\t\t\t\t          >> "+score+" which is the last run is not considered");
		    break;
		}
	//total runs
	        runs=runs+score;
		
     if(runs==100)
	 {
		 System.out.println("\n\t\t\t\t\t\t\t\t          => Congratulations!! Century done");
	 }		 
		
		 }
		    System.out.println("\n\t\t\t\t\t\t\t\t          --------------------------------------------------------");
		   System.out.println("\n\t\t\t\t\t\t\t\t               	    >>> The runs are -:  "+runs+" runs<<<");
		    System.out.println("\n\t\t\t\t\t\t\t\t          --------------------------------------------------------");
	}
	}
	
